// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.24.0
// source: get_token_by_user_id.sql

package repo

import (
	"context"

	"github.com/google/uuid"
)

const getTokenByUserID = `-- name: GetTokenByUserID :one
SELECT user_id, token
FROM tokens
WHERE user_id = $1
`

func (q *Queries) GetTokenByUserID(ctx context.Context, userID uuid.UUID) (Token, error) {
	row := q.db.QueryRowContext(ctx, getTokenByUserID, userID)
	var i Token
	err := row.Scan(&i.UserID, &i.Token)
	return i, err
}
